In [1]:
#script regarding the creation of the "loads.tab" and "lz_peak_loads"
import pandas as pd
import numpy as np
df=pd.read_csv("OrganizedTables/HourlyLoadPerNode.csv",index_col=range(4),header=0)

In [2]:
#creation of an axuliary dataframe for the "loads.tab" file with needed columns
a=pd.DataFrame(index=df.index,columns=['load_area','timepoint','lz_demand_tz'])

In [6]:
#creation of timestamps for the new table
for y in range(2016,2031):
        for m in range(1,13):
            for d in a.xs([y,m,1],level=[0,1,3]).index.tolist():
                for h in range(1,25):
                    a.xs([y,m,d,h])['timepoint']=str(y)+str(m).zfill(2)+str(d).zfill(2)+str(h-1).zfill(2)
time=a['timepoint'].tolist()  
time=pd.DataFrame(time)
time
#del a

                 0
0       2016010100
1       2016010101
2       2016010102
3       2016010103
4       2016010104
5       2016010105
6       2016010106
7       2016010107
8       2016010108
9       2016010109
10      2016010110
11      2016010111
12      2016010112
13      2016010113
14      2016010114
15      2016010115
16      2016010116
17      2016010117
18      2016010118
19      2016010119
20      2016010120
21      2016010121
22      2016010122
23      2016010123
24      2016010200
25      2016010201
26      2016010202
27      2016010203
28      2016010204
29      2016010205
...            ...
131130  2030122918
131131  2030122919
131132  2030122920
131133  2030122921
131134  2030122922
131135  2030122923
131136  2030123000
131137  2030123001
131138  2030123002
131139  2030123003
131140  2030123004
131141  2030123005
131142  2030123006
131143  2030123007
131144  2030123008
131145  2030123009
131146  2030123010
131147  2030123011
131148  2030123012
131149  2030123013
131150  2030123014
131151  2030123015
131152  2030123016
131153  2030123017
131154  2030123018
131155  2030123019
131156  2030123020
131157  2030123021
131158  2030123022
131159  2030123023

[131160 rows x 1 columns]

In [8]:
'''creation of an empty data frame that will receive, by concatenation, 
 a dataframe created for each load zone'''
final=pd.DataFrame()
for k in df.columns.tolist():
    b=pd.DataFrame(index=df.index,columns=['load_area','timepoint','lz_demand_mw'])
    #filling load area column with the load area name
    b['load_area']=k
    #pasting the complete load from that load area to the lz_demand_mw column
    b['lz_demand_mw']=df[k]
    b.set_index('load_area',append=False,inplace=True)
    #paste timestamps in the "timepoint" column
    b['timepoint']=time
    final=final.append(b)

In [9]:
#Import of the tables to another place
final.to_csv("OrganizedTables/loads_mid.csv")
final.to_csv("../../../Main Tabs/csv/loads_mid.csv")
final.to_csv("../../../Main Tabs/loads_mid.tab",sep='\t')

In [3]:
#creation of data frame for the "lz_peak_loads file"
c=pd.DataFrame()
for k in df.columns.tolist():
    #creation of temporary dataframe for every load zone
    d=pd.DataFrame(index=range(3),columns=['load_zone','period','peak_demand_mw'])
    #filling the load zone column with load zone name
    d['load_zone']=k
    #iterating over the periods
    for i in range(3):
        #selecting the period day
        d.loc[i,'period']=2016+(i*5)
        #assigning the maximum demand for that period of 5 years to the "peak demand mw"column
        d.loc[i,'peak_demand_mw']=df.loc[[2016+(i*5),2020+i*5],:][k].max()
    #reset the index to the load_zone
    d.set_index('load_zone',append=False,inplace=True)
    c=c.append(d)

In [4]:
#import
c.to_csv("OrganizedTables/lz_peak_loads_mid.csv")
c.to_csv("../../../Main Tabs/lz_peak_loads_mid.csv")
c.to_csv("../../../Main Tabs/lz_peak_loads_mid.tab",sep='\t')